### ISSUE TITLE
ScreenFlow __getattr__ infinite recursion

### ISSUE THREAD

**Issue by Faylixe** [Faylixe/screenflow#10]
When a **ScreenFlow** instance is created, ``configure_screenflow`` function is called to register default screen factories. It brings an infinite recursion :

```python
>>> screenflow = ScreenFlow()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "screenflow/screenflow.py", line 74, in __init__
    configure_screenflow(self)
  File "screenflow/screens/__init__.py", line 17, in configure_screenflow
    screenflow.register_factory('message', message_screen_factory)
  File "screenflow/screenflow.py", line 179, in register_factory
    if type_name in self.factories.keys():
  File "screenflow/screenflow.py", line 103, in __getattr__
    if name in self.screens.keys():
```

**Comment by Faylixe** [comment]
screens and factories attributes were not initialized before calling ``configure_screenflow``. Resolved by 7e6b5714db55d51169705e9bf591dac9ec5debb4
